name = "TuringBenchmarking"
uuid = "0db1332d-5c25-4deb-809f-459bc696f94f"
authors = ["Tor Erlend Fjelde <tor.erlend95@gmail.com> and contributors"]
version = "0.2.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
LogDensityProblemsAD = "996a588d-648d-4e1f-a8f0-a84b347e47b1"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"

[compat]
BenchmarkTools = "1"
BridgeStan = "2"
LogDensityProblems = "2"
LogDensityProblemsAD = "1"
Requires = "1"
ReverseDiff = "1.14"
Turing = "0.23, 0.24, 0.29"
Zygote = "0.6"
julia = "1.6"

[extensions]
TuringBenchmarkingBridgeStanExt = "BridgeStan"

[extras]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
